### ISSUE TITLE
Add encodeuricomponent

### ISSUE THREAD

**Issue by raf555** [TheRealBarenziah/imgbb-uploader#10]
https://github.com/TheRealBarenziah/imgbb-uploader/blob/a9a6ae5c2dd65add53954ec8e0a116c0eaa6b893/src/postToImgbb.ts#L31

It is a minor problem though, I recommend to clean the `name` argument using `encodeURIcomponent` method to give user a better experience.

**Comment by TheRealBarenziah** [comment]
Thank you very much for raising this! 

I looked into it [a bit](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI#examples), and since imgBB api doesn't have documentation, made [couple tests](https://github.com/TheRealBarenziah/imgbb-uploader/blob/fix-encode-uri/src/postToImgbb.ts#L31) I'd like to share:
```javascript
if (name) query += `&name=${encodeURIComponent(name)}`;
``` 
![FIrst one](https://i.ibb.co/qYfk5DW/image.png)
For this one, the value of encoded `name` was:
```javascript
"Aelora%20%F0%9F%80%84%20%3B%2C%2F%3F%3A%40%26%3D%2B%24%23%20-_.!~*'()%20ABC%20abc%20123"
```
Two couple more little tests :
![Second](https://i.ibb.co/jhynCs4/funky-String2.png)
![Third](https://i.ibb.co/89875pJ/funky-String3.png)

The `encodeURIComponent` will soon make it into master, but I feel the UX you and I care about (and thank you again for that) will also need finding out the exact pattern of their `name` treatment, to put it in the README until they update their ["own"](https://api.imgbb.com/) :)

**Comment by raf555** [comment]
Thank you for providing the test result! I didn't think that far for the filename. My concern for adding this issue in the first place was sometimes I uploaded image with name containing other character than URI component `[A-Za-z0-9-_.!~*'()]` and resulting an exception because it is not encoded. Thus, adding this issue might give user/dev a better experience, I thought.

**Comment by TheRealBarenziah** [comment]
Hello, 
small update, I still didn't have found a satisfying solution for name parsing, but I intend to at least push the `encodeURIComponent` bit this weekend regardless :)

**Comment by raf555** [comment]
Thank you!

**Comment by TheRealBarenziah** [comment]
[I'm closing this](https://github.com/TheRealBarenziah/imgbb-uploader/blob/master/src/postToImgbb.ts#L31) for now, & open a new issue for the distinct name parsing problem
