### ISSUE TITLE
Support Chevereto

### ISSUE THREAD

**Issue by rodber** [TheRealBarenziah/imgbb-uploader#14]
Idea: You could easily extend your project to support Chevereto (the software used by ImgBB) and therefore dramatically extend the reach of this project.

https://github.com/chevereto/chevereto-free

**Comment by TheRealBarenziah** [comment]
Hello rodber, 

thank you for the suggestion! I didn't know Chevereto but Im interested in discovering it; I'll have to play with it a bit before deciding an eventual patch for this module.

I'll leave this issue open to remind me, & to update on the matter. Thanks again for proposal!

**Comment by rodber** [comment]
Chevereto V3 API is compatible with the API included in [Chevereto-Free](https://github.com/chevereto/chevereto-free) so if you really want to setup that kind of test it will be certainly feasible (but a lot of work ahead). In regards to this, [I will provide a Docker image](https://github.com/chevereto/Chevereto-Free/issues/105) for Chevereto-Free V1.5, that should help you to drive these test easier 😉

**Comment by rodber** [comment]
We will introduce 1:1 compatibility with imgbb API for Chevereto V4.0.0.beta.7. https://chevereto.com/community/threads/chevereto-v4-0-0-beta-7.14164/#post-70982 

This means that you only need to change the endpoint to support a configurable value and any Chevereto powered system will be compatible with this.

**Comment by TheRealBarenziah** [comment]
Hey rodber, that's awesome, thanks for letting me know! :heart: 

FYI (and others readers) I still intend to support chevereto 3.x (& final chevereto-free) versions, and am ~75% done, but have encountered many problems trying to seamlessly handle both http & https setups; that's the last difficulty I've yet to solve.

> Basically, they (imgBB) override our standard to exclude other Chevereto users (pretends to be shocked!).

I feel you, and it's bothering me too :( 
That's why I still intend to close this issue the proper way (along the fact I get valuable knowledge out of my struggles)

> you only need to change the endpoint to support a configurable value

It's a nitpick but in my case I'll also need to handle the different API key validation (32 char long for imgBB versus 128+ for chevereto v4).

Anyway, thank you for your work on chevereto, and be assured I'm still working on this issue!

**Comment by rodber** [comment]
> I'll also need to handle the different API key validation (32 char long for imgBB versus 128+ for chevereto v4).

You don't need to validate key lenght because that's outside your layer and is not your responsability. It also adds the useless extra job for you of having to keep updated your implementation if we decide to bump to 256 or if some user edit the source to short it to 20 or whataver.

If you need to store the key use a generic medium text field and don't worry about the key unless it is an empty value.

**Comment by TheRealBarenziah** [comment]
> don't worry about the key unless it is an empty value.

Yeah, about chevereto version you're absolutely right. Actually I won't even check for empty value, since someone could fork the open-source version and make the upload API public. As you say, it's not my responsibility.

I only empathized this because in the case of imgBB API, I **DO** check for 32 char long API key. It is opinionated, yeah, but they never changed their format, and checking for non-null, length 32 string sometimes allows for quicker throw (& save a HTTP request).

Not asking you to change anything! Just wanted you to be aware of the kind of things people may have built upon imgBB, before someone comes complaining about their imgBB code not working anymore.

Cheers!

**Comment by TheRealBarenziah** [comment]
[It's finally done !](https://github.com/TheRealBarenziah/imgbb-uploader/blob/master/USE_WITH_CHEVERETO.md)

- In the end I took your advice about API key and only check if it exists
- My interface should be fine with chevereto v3/v4/forked v3-free/future v4 parameters
- I made my CI on a chevereto-free version, sorry for being this cheap 🙈

Still, thank you again for opening this issue, I've learned quite a bit working on it !

You're now mentioned in the README, it's not much but I hope it can at least raise some awareness about the tech behind imgBB (and the fact that [chevereto-free repo](https://github.com/rodber/chevereto-free) desperately need contributors)

Best of luck with v4 dev! :wave:

**Comment by rodber** [comment]
Looking great, thanks for adding it!

How can I get in contact with you? I want to gift you a V4 license.
