### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by i1Ax** [TheRealBarenziah/imgbb-uploader#18]
![image](https://user-images.githubusercontent.com/59040199/144704898-28de06c4-dad6-4d11-906a-29c117be47d0.png)
![image](https://user-images.githubusercontent.com/59040199/144704908-a5de7654-0438-45c6-9455-698484245083.png)
![image](https://user-images.githubusercontent.com/59040199/144704924-5e57626b-795c-4e49-b721-494e37268c76.png)

**Comment by TheRealBarenziah** [comment]
Hello @i1Ax, thanks for reporting this !

I can't be sure without knowing the file you were using, but I've gotten similar results while uploading a file greater than 32MB.

You can confirm that either by checking the input, or by inserting a console.log in `./node_modules/imgbb-uploader/lib/cjs/postToImgbb.js` line 65: 
```javascript
res.on("end", function () {
  console.log("imgBB response: ", response); // here
  var output = JSON.parse(response).data;
...
```

However, if your file is lighter than that, it'd be intriguing; please provide me the image and snippet of your `imgbbUploader` so I can investigate.

I'll leave this issue open since the error message isn't explicit enough for uploads >32MB - It must be patched in the next release

**Comment by i1Ax** [comment]
![image](https://user-images.githubusercontent.com/59040199/144746139-2e00d586-7dca-46e5-9339-2bf434bfe2a5.png)
![image](https://user-images.githubusercontent.com/59040199/144746182-c81567d1-32a3-4f24-b6dd-8182a2fcd537.png)

After December 1 it is not working
It works without any problems before

**Comment by i1Ax** [comment]
new api 
![image](https://user-images.githubusercontent.com/59040199/144748130-10866c79-2751-4a0f-916a-f9dcf65f7ea6.png)

**Comment by i1Ax** [comment]
i changed the image name and its working perfect now, but i have a question there is any rate limit on imgbb api?
![image](https://user-images.githubusercontent.com/59040199/144748276-937ce4c6-eed0-48cd-97dc-7c1034a05300.png)

**Comment by i1Ax** [comment]
on my pc works
on vps said You have been forbidden to use this website

**Comment by TheRealBarenziah** [comment]
> i changed the image name and its working perfect now, but i have a question there is any rate limit on imgbb api?

I'm not aware of any rate limit, but tbh I never put too much load on their service. The most I've done is ~30 uploads in a few seconds (running my test suite twice in parallel: ~15*2). It's probable they have some kind of limit especially since their service is free, but I don't know the numbers.. Never had any contact with their devs, and their documentation is very scarce 😞 

> on my pc works
> on vps said You have been forbidden to use this website
now this is very strange; are you using the same API key? If it works on your pc I'm afraid the problem lies in the specifics of your vps config

**Comment by i1Ax** [comment]
i didn't violate any tos, i will try make another account .
last question: there is any way to make public api or more than machine is using my api (active in the same time) Does it work without any problems?

I appreciate your help, thank you ❤️

**Comment by TheRealBarenziah** [comment]
If I understand correctly (using the same imgbb API key for several different services), it should work without problem, as long as you don't run into the rate limit.

ImgBB also easily allows having multiple API keys: 
![image](https://user-images.githubusercontent.com/36484411/144757930-82162964-6e8e-45e8-b105-b5ffd58d88f7.png)

But then they're all tied to the same account. Depending what you need, I'd: 
- use a single API key if you use imgbb on a thing like a server OR your own Discord bot
- use multiple API keys bound to same account if you use imgbb API in different contexts (like, your web server, your test suite and your own Discord bot)
- use multiple imgBB accounts if you're afraid of running into some kind of rate limit (multiple API keys are still bound to the same account)
- in the case of a Discord bot you are making available for other, offer the possibility to pass their own imgBB API key through an environment variable or something similar; that way you grant them control and responsibility on their own use of imgBB service. It's more of less the approach of this very module

Hope that helps !

**Comment by TheRealBarenziah** [comment]
I'm closing this issue and opening [a dedicated one](https://github.com/TheRealBarenziah/imgbb-uploader/issues/19) for better error handling. Thanks again for reporting this :)
