### ISSUE TITLE
This is not an Issue, but a question

### ISSUE THREAD

**Issue by williamdarkocode** [TheRealBarenziah/imgbb-uploader#3]
Are there anyways to delete uploaded images using this api?

**Comment by TheRealBarenziah** [comment]
Hello, 

thank for the issue! Made me look further into this. This is what I've found: 

- the value of `delete_url` in response directs on a page where the viewer can see the image & have a button to delete it (without needing for login)  

- imgbb API doesn't seem to provide an endpoint we could easily call to delete things programatically. Afaik nothing changed since [this 2015 SOF answer](https://stackoverflow.com/a/62921975), and it's true that if you need a solid CRUD API and workable media management, there are plenty better free solutions out there.  

- I tried to inspect the request made by clicking on the button on `delete_url`  
It was a **POST** _form-data_ on `https://ibb.co/json`:  
![payload](https://i.ibb.co/0DRX6dd/imgbb.png)  
My ids are most likely bound to the API key I used at the start.  
Afaik this API is undocumented and seem like their private backend. Trying to 'hack' this endpoint doesn't seem reasonable to me, nor does seem the workaround (webscrapping the `delete_url`). Cf dot 2, if needing the full CRUD, you'd gain time looking for a more suitable API.  

- Still, depending your need, we can still work with  
[expiration (optional)](https://api.imgbb.com/)  
`Enable this if you want to force uploads to be auto deleted after certain time (in seconds 60-15552000)`  
It is an accepted parameter on the endpoint we use, so passing that to imgbb-uploader would only take a quick fix.


I'll look into implementing it someday, leave that open and feel free to fork in the meantime :)

**Comment by williamdarkocode** [comment]
No problem; thanks for looking into it. I've since moved to another api (Cloudinary) which does exactly what I want.
