### ISSUE TITLE
How to delete uploaded images from imgbb site

### ISSUE THREAD

**Issue by sandeepg1220** [TheRealBarenziah/imgbb-uploader#32]
Hi,

Unfortunately we uploaded images into imgbb site with an anonymous user. We have only image urls. Delete option is not showing as we uploaded as a anonymous. We have requested imgbb contact support team to delete those images. But no response is getting. Could you please anyone help either with any api we can delete or is there any other way? I am troubling with this please do the needful. 

Thank You!

**Comment by sandeepg1220** [comment]
Any way is there to get the delete_url from image url what we have?

**Comment by TheRealBarenziah** [comment]
Hello

Afaik "anonymous user" implies you uploaded through their website.

I'm not affiliated with them so I can only guess, and have two not-so-useful advices :
- don't wait for their support, they will never come back to you
- there's no guarantee, but there's a fair chance their `image` struct is shared for anonymous & identified uploads. In which case you could either bruteforce, or deduce the pattern for the delete_url, which is always a 32 character string

`"delete_url": "https://ibb.co/b1hBnTC/4a47708a82c6491e0605c0e375f2a7e5"`

It's up to you to decide if hacking this is worth your time

Closing the issue since it's not a problem you can have using `imgbb-uploader`, since it requires an API key, which itself requires an account (where you can delete stuff as needed)

Good luck to you! If you find a solution feel free to share it, since imgbb API documentation is so scarce and precious
